# Generated by Django 3.1.4 on 2021-02-06 01:12

import connect4.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connect4Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state', models.JSONField(default=connect4.models.Connect4Game.initilizeBoard)),
                ('player1', models.CharField(default='', max_length=100)),
                ('player2', models.CharField(default='', max_length=100)),
                ('numPlayer1Connections', models.IntegerField(default=0)),
                ('numPlayer2Connections', models.IntegerField(default=0)),
            ],
        ),
    ]
