# Generated by Django 3.1.4 on 2021-02-03 20:17

import connect4.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connect4Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state', models.JSONField(default=connect4.models.Connect4Game.initilizeBoard)),
                ('player1', models.PositiveIntegerField(blank=True, null=True)),
                ('player2', models.PositiveIntegerField(blank=True, null=True)),
                ('player1_connected', models.BooleanField(default=False)),
                ('player2_connected', models.BooleanField(default=False)),
            ],
        ),
    ]
